name: Version and Publish

on:
  workflow_call:
    inputs:
      version-type:
        required: false
        type: string # possible values: major, minor, patch
        default: patch  
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Type of version bump'
        default: patch
        required: true
        type: choice 
        options:
          - patch
          - minor
          - major

jobs:
  version-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Bump version
        run: npm version ${{ inputs.version-type }} --no-git-tag-version

      - name: Test flow
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git checkout -b bump-version
          git add .
          git commit -am "Bump version for ${{ inputs.version-type }} release"
          git push origin bump-version
          gh pr create --title "Bump version for ${{ inputs.version-type }} release" --body "This PR bumps the version for a ${{ inputs.version-type }} release." --base main --head bump-version
          gh pr merge --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      
